### ISSUE TITLE
tokio-runtime-worker panicked

### ISSUE THREAD

**Issue by M-Patrone** [sreeise/graph-rs#394] opened 2023-02-13 23:21 UTC
I am having an issue with accessing the Graph API. I am attempting to use the access token for a background task, however how can I get the access_token out from the redirect-method.
 
I have done some research and found that a user with a similar issue, @kitplummer, had reported this problem on the GitHub page for "graph-rs" (https://github.com/sreeise/graph-rs/issues/373). I also tried changing "Graph::new" to "Graph::new_async" but was unable to resolve the issue.

Please note that I am new to Rust programming language and I would appreciate your help in resolving this matter.

@kitplummer I was wondering if you could possibly share your solution with me on how you solved the problem of graceful shutdown with warp. I would greatly appreciate it if you could provide some insights into your approach.

```Rust

fn create_oauth() -> OAuth {
    let client_id = std::env::var("CLIENT_ID").expect("CLIENT_ID must be set.");
    let client_secret = std::env::var("CLIENT_SECRET").expect("CLIENT_SECRET must be set.");
    let mut oauth = OAuth::new();
    oauth
        .client_id(&client_id)
        .client_secret(&client_secret)
        .add_scope("MailboxSettings.ReadWrite")
        .redirect_uri("http://localhost:8000/redirect")
        .authorize_url("https://login.microsoftonline.com/common/oauth2/v2.0/authorize")
        .access_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token")
        .refresh_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token")
        .response_type("code");
    oauth
}

#[tokio::main]
async fn main() {
    dotenv().ok();
    start_server_main().await;
}
pub async fn start_server_main() {
    let query = warp::query::<AccessCode>()
        .map(Some)
        .or_else(|_| async { Ok::<(Option<AccessCode>,), std::convert::Infallible>((None,)) });

    let routes = warp::get()
        .and(warp::path("redirect"))
        .and(query)
        .and_then(handle_redirect);

    let mut oauth = create_oauth();
    let mut request = oauth.build_async().authorization_code_grant();
    request.browser_authorization().open().unwrap();

    warp::serve(routes).run(([127, 0, 0, 1], 8000)).await;
}

async fn handle_redirect(
    code_option: Option<AccessCode>,
) -> Result<Box<dyn warp::Reply>, warp::Rejection> {
    match code_option {
        Some(access_code) => {
            println!("{:#?}", access_code);

            set_and_req_access_code(access_code).await;

            Ok(Box::new(
                "Successfully Logged In! You can close your browser.",
            ))
        }
        None => Err(warp::reject()),
    }
}


pub async fn set_and_req_access_code(access_code: AccessCode) {
    let mut oauth = create_oauth();

    oauth.access_code(access_code.code.as_str());
    let mut request = oauth.build_async().authorization_code_grant();

    let access_token = request.access_token().send().await.unwrap();

    let client = Graph::new_async(access_token.bearer_token());

    let json = serde_json::json!({
    "requests": [
        {
            "id": "1",
            "method": "GET",
            "url": format!("/me/mailboxSettings/automaticRepliesSetting")
        }
        ]
    });

    let mut recv = client.v1().batch(&json).send().await;

    loop {
        match recv.recv().await {
            Some(delta) => match delta {
                Delta::Next(response) => {
                    println!("{:#?}", response);
                }
                Delta::Done(err) => {
                    if let Some(err) = err {
                        println!("Error: {:#?}", err);
                        println!("Description: {:#?}", err);
                    }
                    break;
                }
            },
            None => {
                println!("recv_result is None");
                break;
            }
        }
    }
}

```

**Comment by sreeise** [comment] 2023-02-15 11:48
HI @M-Patrone 

Could you possibly provide some more details on the error or issue you are seeing? That will help to figure out whats going on. I am not exactly sure what the issue is from your post right now.

**Comment by M-Patrone** [comment] 2023-02-16 21:47
Dear @sreeise 

Thank you very much for your prompt response. I wanted to let you know that I have successfully resolved the error.

I do have a follow-up question regarding how to stop the warp server from using the access token in a background task. How can I accomplish that? (which is why I mentioned kitplummer)

Would it be correct for me to assume that I need to create a new OAuth instance with the current access token in order to obtain a refresh token?

**Comment by sreeise** [comment] 2023-02-18 03:05
> Dear @sreeise
> 
> Thank you very much for your prompt response. I wanted to let you know that I have successfully resolved the error.
> 
> I do have a follow-up question regarding how to stop the warp server from using the access token in a background task. How can I accomplish that? (which is why I mentioned kitplummer)
> 
> Would it be correct for me to assume that I need to create a new `OAuth` instance with the current access token in order to obtain a refresh token?

Glad to hear you resolved the issue. 

As far as creating a new OAuth instance, you don't necessarily have to create a new one if you have the original one that you used to get an access token. As long as the OAuth flow you used returned a refresh token along with the access token when you use the original instance it will have the original access/refresh token and you can just call `oauth_client.refresh_token()` which will give you the request that you can call to get a refresh token.

If you don't have the original instance, what you can do is create a new instance like you mentioned and provide it the access token in the form of the struct `AccessToken`. 
https://github.com/sreeise/graph-rs/blob/3cb16fba06cea812410a0fd5f74127ce89a529bf/graph-oauth/src/auth.rs#L844

Now that I am thinking about it that might not be the easist way to use the client given that you may just want to provide the refresh token to the client instead of the whole access token struct. But thats something that can be added.

**Comment by sreeise** [comment] 2023-04-02 20:42
@M-Patrone Gonna close this one out since it sounds like you figured out what the issue was. Let me know if not.

**Closed by sreeise** 2023-04-02 20:42 UTC
